### ISSUE TITLE
Best way to provide OcflStorage implementations for cloud providers

### ISSUE THREAD

**Issue by kenoir** [pwinckles/ocfl-java-core#2]
What's the best way to provide an implementation on `OcflStorage` for a cloud provider object store e.g. Amazon S3 or Azure Blob store?

**Comment by pwinckles** [comment]
You would need to write an implementation similar to `FileSystemOcflStorage.java` (https://github.com/pwinckles/ocfl-java-core/blob/master/src/main/java/edu/wisc/library/ocfl/core/storage/FileSystemOcflStorage.java)

And then plug it in in the `new OcflRepositoryBuilder().build()` call.

A couple of notes:

1. I am planning on adding cloud storage integration at some point, but there's nothing preventing you from writing your own now.
2. Neither the OCFL spec nor this library are "release" versions. You're welcome to use them now, but do so knowing that there may be significant changes prior to release.

**Comment by pwinckles** [comment]
@kenoir I moved the code to https://github.com/UW-Madison-Library/ocfl-java . I have not started implementing cloud storage yet, but when I do it will be in the new repository location.
